name: Core
version: 18.2.1-dev
main: core.core.CoreMain
api-version: 1.13
load: STARTUP
loadbefore: [SetPosition, Lobby, Challenge]
commands :
  Gamemode:
    description: changes the Gamemode of the User
    aliases: [gm]
  Weather:
    description: changes the weather on the Server
  time:
    description: changes the time on the server
  core:
    description: show information on the CorePlugin
  allow:
    description: lets every op set the permission to use other commands
  revoke:
    description: takes away the power to use commands
  hub:
    aliases: [l,lobby]
    description: moves player to Lobby
  heal:
    description: heals the Player
  difficulty:
    description: sets difficulty in world
  tps:
    description: show recent tps
  advancements:
    description: show or hide the advancement message
  invsee:
    description: see inv of player
  ping:
    description: get ping of player
  permissions:
    description: set and get permissions
  setHP:
    description: set hp of player
  teleport:
    aliases: [tp]
  reload:
    aliases: [r]
  reboot:
    description: reboot server
  sql:
    description: manage sql database
  bug:
    description: report bug on GH
  schedule:
    description: schedule text for hotbar
